
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 02 20:20:58 CEST 2017
//----------------------------------------------------

package pp1.vl130298;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOEQ = 35;
  public static final int CONST = 7;
  public static final int LPAREN = 40;
  public static final int SEMI = 38;
  public static final int LSS = 25;
  public static final int FOR = 8;
  public static final int MINUS = 19;
  public static final int RPAREN = 41;
  public static final int STATIC = 5;
  public static final int AND = 29;
  public static final int OR = 30;
  public static final int BOOL = 49;
  public static final int COMMA = 39;
  public static final int PEQ = 31;
  public static final int CLASS = 3;
  public static final int INC = 36;
  public static final int DIV = 21;
  public static final int MUEQ = 33;
  public static final int CONTINIUE = 10;
  public static final int GEQ = 28;
  public static final int PLUS = 18;
  public static final int IF = 11;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int GTR = 27;
  public static final int EQUAL = 17;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 20;
  public static final int NUMBER = 47;
  public static final int MOD = 22;
  public static final int NEQ = 24;
  public static final int IDENT = 48;
  public static final int BREAK = 9;
  public static final int VOID = 6;
  public static final int EQU = 23;
  public static final int LBRACE = 42;
  public static final int MEQ = 32;
  public static final int ELSE = 12;
  public static final int READ = 14;
  public static final int DEQ = 34;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 4;
  public static final int LEQ = 26;
  public static final int QLBRACE = 44;
  public static final int DEC = 37;
  public static final int ASCII = 50;
  public static final int PRINT = 13;
  public static final int QRBRACE = 45;
}

